NewsShow/NewsShow/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from news import views



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/',include('news.urls',namespace = 'news')),
    url(r'^search/$',views.search),
]

NewsShow/news/urls.py
from django.conf.urls import url

from news import views

urlpatterns = [
    url(r'^search-form/(\d{1,4})/$',views.search_form),
    url(r'^news_show/(\d{1,4})/$',views.news_show,name = 'news_show'),
    #url(r'^search/page\d{1,4}/',views.search),
    url(r'^search/(\d{1,4})/',views.search),
]

NewsShow/news/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class news(models.Model):
	title = models.CharField(max_length = 50)
	time = models.CharField(max_length = 14)
	author = models.CharField(max_length = 20)
	body = models.TextField()
	breakwords = models.TextField()
	keywords = models.TextField()
	recommend = models.TextField()
	def __str__(self):
		return self.title


# Create your models here.

NewsShow/news/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
# news.page import PageInfo
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import time
import sqlite3
import re
from .models import news
import jieba
import re

def search_form(request,pagenum):
	allnews = news.objects.all()
	pag = Paginator(allnews, 10)
	newslist = pag.page(pagenum)
	return render(request,'search_form.html',{'all_news':newslist})

def search(request,pagenum):
	q = request.GET['q']
	pattern = '(\d{4})-(\d{1,2})-(\d{1,2})'
	begin = '2015-09-15'
	endday = '2018-09-15'
	if 'begin' in request.GET:
		begin = request.GET['begin']
		res = re.search(pattern,begin)
		if res:
			year = res.group(1)
			yue = res.group(2)
			ri = res.group(3)
			if len(yue) == 1:
				yue = '0'+yue
			if len(ri) == 1:
				ri = '0'+ri
			begin = year+'-'+yue+'-'+ri
		else:
			begin = '2015-09-15'
	else: 
		begin = '2015-09-15'
	if 'end' in request.GET:
		endday = request.GET['end']
		res = re.search(pattern,endday)
		if res:
			year = res.group(1)
			yue = res.group(2)
			ri = res.group(3)
			if len(yue) == 1:
				yue = '0'+yue
			if len(ri) == 1:
				ri = '0'+ri
			endday = year+'-'+yue+'-'+ri
		else:
			endday = '2018-09-15'
	else: 
		endday = '2018-09-15'
	wordlist = list(jieba.cut(q))
	for word in wordlist:
		word = word.strip()
	allnews =[]
	start = time.clock()
	allnewstemp = news.objects.all()
	all_news = []
	for item in allnewstemp:
		if item.time >= begin and item.time <= endday:
			all_news.append(item)

	dictnum = {}
	if len(wordlist)>=3: 
		for word in wordlist:
			if len(word) == 1:
				wordlist.remove(word)

	if len(wordlist) == 1:
		for item in all_news:
			if q in item.title:
				allnews.append(item)
		for item in all_news:
			if q in item.body:
				allnews.append(item)
	else:		
		max = 0		
		for item in all_news:
			num = 0
			for word in wordlist:
				if word in item.title:
					num += 1
			if num > max : 
				max = num
			if dictnum.has_key(num):
				dictnum[num].append(item)
			else:
				dictnum[num]=[]
				dictnum[num].append(item)
		while max > 0:
			if dictnum.has_key(max):
				allnews.extend(dictnum[max])
			max -= 1
		max = 0
		dictnum = {}
		for item in all_news:
			num = 0
			for word in wordlist:
				if word in item.body:
					num += 1
			if num > max : 
				max = num
			if dictnum.has_key(num):
				dictnum[num].append(item)
			else:
				dictnum[num]=[]
				dictnum[num].append(item)
		while max > 0:
			if dictnum.has_key(max):
				for n in dictnum[max]:
					if n not in allnews:
						allnews.append(n)
			max -= 1
	endtime = time.clock()
	timing = endtime - start
	all_count =len(allnews)
	pag = Paginator(allnews, 10)	
	if pag.num_pages>10:
		page = int(pagenum)
		if page-5<1:
			pageRange=range(1,11)
		elif page+5>pag.num_pages:
			pageRange=range(page-5,pag.num_pages+1)
		else:
			pageRange=range(page-5,page+5)
	else:
		pageRange=pag.page_range
	newslist = pag.page(pagenum)
	return render(request,"search_result.html",{'begin':begin,'end':endday,'all_news':newslist,'time':timing,'word':q,'num':all_count,'keywl':wordlist,'range':pageRange})

def news_show(request,offset):
	try:
		index = int(offset)		
		con = sqlite3.connect('/Users/kingjames/Desktop/NewsShow/db.sqlite3')
		c = con.cursor()
		p = news.objects.get(id = index)
		#data = c.execute("SELECT title, time,author,body from news_news where id = index" )
		title = p.title
		title = title.replace("&nbsp;"," ")
		title = title.replace("&quot;",'"')
		time = p.time
		author = p.author
		tempbody = p.body
		tempbody = tempbody.replace("&nbsp;"," ")
		tempbody = tempbody.replace("&quot;",'"')
		body = tempbody.split('\n')
		temprec = p.recommend
		rec = temprec.split()
		
		p1 = news.objects.get(id = int(rec[0]))
		p2 = news.objects.get(id = int(rec[1]))
		p3 = news.objects.get(id = int(rec[2]))
		
		#return renddayer(request,'news_show.html',{'title':title})
		#return renddayer(request,"news_show.html",{'title':title,'time':time,'author':author,'body':body,'index':rec})
		return render(request,"news_show.html",{'title':title,'time':time,'author':author,'body':body,'first':p1,'second':p2,'third':p3})
	except ValueError:
		raise Http404()


# Create your views here.

NewsShow/news/templates/news_show.html
<html>
<head>
	<title>news_show</title>
</head>
<body>
	<BODY bgcolor = white>
<style>
    .font_02 { font-size:35px;}
  </style>
	<p><strong><center class="font_02">{{ title }}</center></strong></p>
	<p><center>发布时间：{{time}}               来源：{{author}}</center></p>
	<div style="width: 60%;margin:3 auto;border: 2px solid black">
		{% for item in body %}
		<p>{{item}}</p> 
		{%endfor%}
	</div>
	<div>
		<h1><center> Recommend </center></h1>
		<p><a href="{% url 'news:news_show' first.id %}" target="_blank" class = "font_01" ><center>{{first.title}}</center></a></p>
		<p><a href="{% url 'news:news_show' second.id %}" target="_blank" class = "font_01" ><center>{{second.title}}</center></a></p>
		<p><a href="{% url 'news:news_show' third.id %}" target="_blank" class = "font_01" ><center>{{third.title}}</center></a></p>
	</div>
</body>
</html>

NewsShow/news/templates/search_form.html
<html>
<head>
	<title>Search</title>
</head>
<body>
	<h1 style="margin-top: 200px;"><center>搜搜看看，你就知道</center></h1>
	<table>
	<tr>
	<form action="/news/search/1/" method = "get">
		<th><input type="text" name="q"
		style="margin-left : 300px;margin-top: 0px;width: 1000px;height: 50px;font-size: 30px;border: #DCDCDC solid;"></th>
		<th><input type="submit" style="width: 150;height: 50;border: 2px #8470FF solid;font-size: 20px" value="搜索看看"></th>
	</form>
</tr>
</table>
	<p><center>共计3568条新闻</center></p>
<div id = "result" style="border: 2px solid black;width:60%;text-align: center;margin: 2 auto">
	{% for onenews in all_news %}
    <div >
    	<a href="{% url 'news:news_show' onenews.id %}" target="_blank" class = "font_01" ><center>{{onenews.title}}</center></a>
    </div>
    <p></p>
    <p></p>
	{%endfor%}
	<div class="page" style="text-align: center;">
	<td colspan="3" style="text-align: center;">           
               <a href="/news/search-form/1/">首页</a>
         </td>
	<td colspan="3" style="text-align: center;">
            {% if all_news.has_previous %}
               <a href="/news/search-form/{{all_news.previous_page_number}}/">上一页</a>
            {% else %}
               <span>上一页</span>
            {% endif %}
         </td>
    <td colspan="3" style="text-align: center;">
                {% if all_news.has_next %}
               <a href="/news/search-form/{{all_news.next_page_number}}/">下一页</a>
            {% else %}
               <span>下一页</span>
            {% endif %}
         </td> 
    </div>    
</div>
</body>
</html>

NewsShow/news/templates/search_result.html
<html lang="en">
<head>
 <meta charset="UTF-8">
 <title>news</title>
 <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.css">
</head>
<body>
  <form action="/news/search/1/" method = "get" style="margin-top: 15px;">
  <table style="margin-left: 100px">
		<th><input type="text" name="q"  style="width: 500px;height: 50px;margin-top: 10px;font-size: 28px;border: 2px #DCDCDC solid;"></th>
		<th><input type="submit" style="width: 200px;font-size: 25px;height: 45px;margin-top: 13px;border:2px #8470FF solid ;" value="搜搜看看"></th>  
    <th style="margin-left: 100px"> 时间检索：起始于<input type="text" name="begin"  style="width: 150px;height: 40px;font-size: 28px;border: 2px #DCDCDC solid;"> 
        终止于 <input type="text" name="end"  style="margin-top: 15px;width: 150px;height: 40px;font-size: 28px;border: 2px #DCDCDC solid;">
    </th>
</table>
</form>
    <style>
    .font_02 { font-size:28px;}
  </style>
    
      <form action="/news/search/1/" method = "get" style="margin-left: 100px">
          
      </form>
    <h1 class="font_02" style="margin-left: 100px">搜索关键词：{{word}}  时间起始于{{begin}}，终止于{{end}} </h1>
    <h1 class="font_02" style="margin-left: 100px">一共为您找到{{num}}条结果，共用时{{time}}秒</h1>  
    <style>
		.font_01 { font-size:24px;}
	</style>
	<div id = "result">
	{% for onenews in all_news %}
    <div style="margin-left: 100px">
    	<a href="{% url 'news:news_show' onenews.id %}" target="_blank" class = "font_01" >{{onenews.title}}</a>
    	<p>发布时间：{{onenews.time}}  来源：{{onenews.author}}</p>
    <style type=""text/css"">
	.dd
	{
		overflow:hidden;
		text-overflow:ellipsis;
		display:-webkit-box;
		-webkit-box-orient:vertical;
		-webkit-line-clamp:2;
	}	
	</style>
    <div CLASS = "dd" style="width: 50%">
    	{{onenews.body}}
    </div>
    </div>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
	{%endfor%}
</div>
   <table style="margin-left: 200px;margin-top: 50px;margin-bottom: 30px;font-size: 28px" >
   <tr>
         <td colspan="3" >
            {% if all_news.has_previous %}
               <a href="/news/search/{{all_news.previous_page_number}}/?q={{word}}">上一页</a>
            {% else %}
               <span>上一页</span>
            {% endif %}
         </td>
         <td colspan="3" >
            {% for i in range %}
               {% if i == all_news.number %}
                  <span>{{i}}</span>
               {% else %}
                  <a href="/news/search/{{i}}/?q={{word}}">{{i}}</a>
               {% endif %}
            {% endfor %}
         </td>
         <td colspan="3" >
                {% if all_news.has_next %}
               <a href="/news/search/{{all_news.next_page_number}}/?q={{word}}">下一页</a>
            {% else %}
               <span>下一页</span>
            {% endif %}
         </td>
      </tr>
    </table>
</div>
</body>
</html>


<script>
            function keyLight(id, key, bgColor){
              var oDiv = document.getElementById(id),
                  sText = oDiv.innerHTML,
                  bgColor = bgColor || "orange",
                  sKey = "<span style='color: "+bgColor+";'>"+key+"</span>",
                  num = -1,
                  rStr = new RegExp(key, "g"),
                  rHtml = new RegExp("\<.*?\>","ig"), 
                  aHtml = sText.match(rHtml); 
              sText = sText.replace(rHtml, '{~}');  
              sText = sText.replace(rStr,sKey); 
              sText = sText.replace(/{~}/g,function(){  
                num++;
                return aHtml[num];
              });

              oDiv.innerHTML = sText;
            }
            {% for keyw in keywl %}
            var key1 = keyLight('result', '{{ keyw }}', 'red')
            {% endfor %}
</script>